<?php

namespace App;

use App\Mail\ExpenseAdded;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Expense extends Model
{
    //for protecting from mass assaiment // some hacker try to add input field like id in html
    protected $fillable = [
        'user_id' ,
        'expense_name' ,
        'price' ,
        'category' ,
        'comment' ,
    ] ;

//    protected $guarded = [] ;
    public function owner(){//return expenses which belongs to that user
        return $this->belongsTo(User::class);
    }
    public function user(){//return expenses which belongs to that user
        return $this->belongsTo(User::class);
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

//        static::created(function ($expense){
//
//            //        to($expense->owner->user_name)
//            Mail::to(User::first()->user_name)->send(
//                new ExpenseAdded($expense)
//            );
//        });

    }
}
