<?php

namespace App;

use App\Mail\UserSignedup;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Mail;

class User extends Authenticatable
{
    use Notifiable; // $user->notify(new SuccessfullSignedup);

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name' ,
        'second_name' ,
        'user_name' ,
        'hashed_password' ,
        'background_image' ,
    ] ;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function Expenses(){//return expenses which belongs to that user
        return $this->hasMany(Expense::class,'user_id');
    }
    public function Backgrounds(){//return backgrounds which belongs to that user
        return $this->hasMany(Background::class,'user_id');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($user){
//            Mail::to('khaledmostafa297@gmail.com')->send(
//
//                new UserSignedup($user)
//            );
        });
    }

//    $users->filter(function ($user){
//        return $user->isVerified();
//});
    public function isVerified(){
        return (bool)$this->created_at ;
    }
    public function getPasswordAttribute()
    {
        return $this->hashed_password;
    }
}
